export const FEATCH_PERSON = 'FEATCH_PERSON';
export const FEATCH_PERSON_FAIL = 'FEATCH_PERSON_FAIL';
export const FEATCH_PERSON_SUCCESS = 'FEATCH_PERSON_SUCCESS';

export const FEATCH_PERSON_POSTS = 'FEATCH_PERSON_POSTS';
export const FEATCH_PERSON_POSTS_FAIL = 'FEATCH_PERSON_POSTS_FAIL';
export const FEATCH_PERSON_POSTS_SUCCESS = 'FEATCH_PERSON_POSTS_SUCCESS';

export const ON_SHOW_MODAL_POST = 'ON_SHOW_MODAL_POST';
