export const FEATCH_PERSON = 'FEATCH_PERSON';
export const FEATCH_PERSON_FAIL = 'FEATCH_PERSON_FAIL';
export const FEATCH_PERSON_SUCCESS = 'FEATCH_PERSON_SUCCESS';

export const FEATCH_PERSON_POSTS = 'FEATCH_PERSON_POSTS';
export const FEATCH_PERSON_POSTS_FAIL = 'FEATCH_PERSON_POSTS_FAIL';
export const FEATCH_PERSON_POSTS_SUCCESS = 'FEATCH_PERSON_POSTS_SUCCESS';

export const FEATCH_PERSON_POST = 'FEATCH_PERSON_POST';
export const FEATCH_PERSON_POST_FAIL = 'FEATCH_PERSON_POST_FAIL';
export const FEATCH_PERSON_POST_SUCCESS = 'FEATCH_PERSON_POST_SUCCESS';

export const FEATCH_PERSON_ALBUMS = 'FEATCH_PERSON_ALBUMS';
export const FEATCH_PERSON_ALBUMS_FAIL = 'FEATCH_PERSON_ALBUMS_FAIL';
export const FEATCH_PERSON_ALBUMS_SUCCESS = 'FEATCH_PERSON_ALBUMS_SUCCESS';
