export const FEATCH_POSTS = 'FEATCH_POSTS';
export const FEATCH_POSTS_ERROR = 'FEATCH_POST_ERROR';
export const FEATCH_POSTS_SUCCESS = 'FEATCH_POSTS_SUCCESS';

export const FEATCH_POST = 'FEATCH_POST';
export const FEATCH_POST_ERROR = 'FEATCH_POS_ERROR';
export const FEATCH_POST_SUCCESS = 'FEATCH_POST_SUCCESS';
